### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by maciekmisko** [damianniemiec/fs1pg#3]
Hi,
I just wanted to check if it's still working fo you. I tried setting it up and no luck. I see plug listed in enities but switching it does nothing.

What I did:
- created a folder in custom_components
- copied in all files
- added entry in configuration.yaml as per readme

**Comment by damianniemiec** [comment]
Hi, 

I've just checked plugin code and fixed some problems with permissions when broadcasting. Also I've added new configuration option `broadcast` to correct socket settings.

And last but not least I've changed repository structure so now it can be installed with HACS.

Check new version and let me know if it works for you.

**Comment by maciekmisko** [comment]
Thx. I managed to install via HACS. Unfortunately it's still not working for me. My configuration below. IP and MAC were taken from router config page.

```
switch:
  - platform: fs1pg
    device_name: Farelka # name
    broadcast: false # set to true if broadcst
    ip: "192.168.1.180" # plug ip address (could be network broadcast address like 192.168.0.255)
    mac: "xx:xx:xx:xx:xx:xx" # plug MAC address
    scan_interval: 10 # update interval
```
